fix: wallet cold/hot status issue
ArdentHQ/platform-sdk pull request #91
Opened 2024-05-27 18:37 UTC by alfonsobries

https://app.clickup.com/t/86dtjpcuz

The condition used to only apply to transactions that return `true` for `isSent` or `isConfirmed`. During my test, all transactions in my wallet returned false for both, which kept all my wallets as "cold." This was incorrect.

From my understanding, a wallet should be considered hot once it has any transaction, but it’s better to double-check.

2024-05-28 08:32 UTC, ItsANameToo requested changes

2024-05-28 08:32 UTC, ItsANameToo commented on packages/profiles/source/transaction-index.ts
> +			this.#wallet.data().set(WalletData.Status, WalletFlag.Hot);
a cold wallet is a wallet that has not sent anything. Once the wallet itself has an outgoing transaction it should be considered hot, so it's not related to any incoming transactions to it

2024-05-28 17:17 UTC, alfonsobries commented
@ItsANameToo fixed, in case you're curious, the problem was that it was checking if the transaction was sent before assigning the address/public key, which are necessary to determine if it is sent. By adjusting the order, the problem was fixed.

2024-05-29 13:42 UTC, ItsANameToo approved these changes

2024-05-29 13:42 UTC, merged